=== Viswa115/XMLAssignment2/freelancer.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT freelancer-data (freelancer)+>
<!ATTLIST freelancer-data
  xmlns CDATA #FIXED ''
  xmlns:xsi CDATA #FIXED 'http://www.w3.org/2001/XMLSchema-instance'
  xsi:noNamespaceSchemaLocation CDATA #REQUIRED>

<!ELEMENT freelancer (name,qualification,freelancer-in,age,email,
                      shortbio)>
<!ATTLIST freelancer
  xmlns CDATA #FIXED ''
  id NMTOKEN #REQUIRED>

<!ELEMENT name (#PCDATA)>
<!ATTLIST name
  xmlns CDATA #FIXED ''>

<!ELEMENT qualification (#PCDATA)>
<!ATTLIST qualification
  xmlns CDATA #FIXED ''>

<!ELEMENT freelancer-in (#PCDATA)>
<!ATTLIST freelancer-in
  xmlns CDATA #FIXED ''>

<!ELEMENT age (#PCDATA)>
<!ATTLIST age
  xmlns CDATA #FIXED ''>

<!ELEMENT email (#PCDATA)>
<!ATTLIST email
  xmlns CDATA #FIXED ''>

<!ELEMENT shortbio (#PCDATA)>
<!ATTLIST shortbio
  xmlns CDATA #FIXED ''>

=== Viswa115/XMLAssignment2/freelancers.xml
<?xml version="1.0"?>
<!DOCTYPE freelancer-data SYSTEM "freelancer.dtd">
<freelancer-data 
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
      xsi:noNamespaceSchemaLocation="./freelancer.xsd">
  <freelancer id="flr101">
      <name>Yogith</name>
      <qualification>B.Tech</qualification>
      <freelancer-in>Photography</freelancer-in>
      <age>20</age>
      <email>yogith@gmail.com</email>
      <shortbio>I am creative in abstract photography</shortbio>
   </freelancer>
   <freelancer id="flr102">
      <name>Kumaresh</name>
      <qualification>B.Tech</qualification>
      <freelancer-in>Web Development</freelancer-in>
      <age>20</age>
      <email>kumaresh@gmail.com</email>
      <shortbio>I develop web apps with a friendly UI </shortbio>
   </freelancer>
   <freelancer id="flr103">
      <name>Viswa</name>
      <qualification>B.Tech</qualification>
      <freelancer-in>Art and Designing</freelancer-in>
      <age>20</age>
      <email>viswa@gmail.com</email>
      <shortbio>Interested in potrait drawings</shortbio>
   </freelancer>
   <freelancer id="flr104">
      <name>Ramesh</name>
      <qualification>M.Tech</qualification>
      <freelancer-in>Photography</freelancer-in>
      <age>23</age>
      <email>ramesh@gmail.com</email>
      <shortbio>I am creative in abstract photography</shortbio>
   </freelancer>
   <freelancer id="flr105">
      <name>Suresh</name>
      <qualification>M.E</qualification>
      <freelancer-in>API Development</freelancer-in>
      <age>25</age>
      <email>suresth@gmail.com</email>
      <shortbio>I develop API and troubleshoot and support API problems</shortbio>
   </freelancer>
</freelancer-data>
